services:
  app:
    build: 
      context: .
      dockerfile: Dockerfile
    container_name: python_app
    ports:
      - "8000:8000"  # Adjust as needed
    env_file:
      - .env
    volumes:
      - ./app:/app  # Mount local code for development
    # command: "python manage.py runserver 0.0.0.0:8000"
    depends_on:
      - db
  
  db:
    image: postgres:15
    container_name: postgres_db
    environment:
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_NAME}
    ports:
      - "5432:5432"